# Generated by Django 5.2.7 on 2025-11-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='patient_insc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('Sexe', models.CharField(default='', max_length=1)),
                ('NumTel', models.IntegerField()),
            ],
        ),
    ]
