# Generated by Django 5.2.7 on 2025-11-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='patient_auth',
            new_name='emp_auth',
        ),
        migrations.RenameModel(
            old_name='patient_insc',
            new_name='emp_insc',
        ),
    ]
