# Generated by Django 5.2.7 on 2025-11-09 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_patient_auth_emp_auth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='psy_insc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('fichiers', models.FileField(upload_to='fichiers')),
            ],
        ),
        migrations.RenameModel(
            old_name='emp_insc',
            new_name='patient_insc',
        ),
    ]
