# Generated by Django 5.2.7 on 2025-11-09 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_psy_insc_fichiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='psy_insc',
            name='fichiers',
            field=models.FileField(default=django.utils.timezone.now, upload_to='fichiers'),
            preserve_default=False,
        ),
    ]
