# Generated by Django 5.2.7 on 2025-11-10 18:00

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_psy_insc_fichiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psy_insc',
            name='fichiers',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=''),
        ),
    ]
