# Generated by Django 5.2.7 on 2025-11-11 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_psy_insc_fichiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='psy_insc',
            name='Photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='photo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emp_auth',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient_insc',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='psy_insc',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='psy_insc',
            name='fichiers',
            field=models.FileField(upload_to='fichiers'),
        ),
    ]
