# Generated by Django 5.2.7 on 2025-11-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_psy_insc_photo_alter_emp_auth_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psy_insc',
            name='Photo',
        ),
    ]
