# Generated by Django 5.2.7 on 2025-11-11 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rdv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rdv',
            name='Date',
        ),
        migrations.AddField(
            model_name='rdv',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
