# Generated by Django 5.2.7 on 2025-11-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_rdv_date_rdv_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
