# Generated by Django 5.2.7 on 2025-11-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rdv_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfPsy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField()),
                ('photo', models.ImageField(upload_to='')),
                ('desc', models.CharField()),
            ],
        ),
    ]
