# Generated by Django 5.2.7 on 2025-11-12 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_confpsy'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdv',
            name='DocName',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
