# Generated by Django 5.2.7 on 2025-11-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rdv_docname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient_insc',
            old_name='email',
            new_name='my_email',
        ),
        migrations.RenameField(
            model_name='patient_insc',
            old_name='password',
            new_name='my_password',
        ),
    ]
